sudo: true
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# Tasks before the automated installation process of this project.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgmp3-dev
  - git config --global user.name "TravisCI"
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - "dzil authordeps --missing | xargs cpanm --quiet --notest"

# Automated installation tasks of this project.
install:
  - "dzil listdeps --missing | xargs cpanm --quiet --notest"

# Finally perform the test.
script: "dzil test --all"
